### ISSUE TITLE
不更新了吗？

### ISSUE THREAD

**Issue by socpio** [BoyceLig/Clash_Chinese_Patch#10]
新版本什么时候发？

**Comment by AU-Linsanity** [comment]
哈哈哈 同求

**Comment by BoyceLig** [comment]
新版本我暂时还不会汉化，等出教程了  我学会了 再继续

**Comment by isArtJay** [comment]
> 新版本什么时候发？

![image](https://user-images.githubusercontent.com/48620527/99214796-13b0bb00-280c-11eb-9d0e-43ea92f82447.png)
[by HoldOnBro](https://github.com/HoldOnBro/LocalizeCFW#%E6%97%A0%E9%99%90%E6%9C%9F%E5%81%9C%E6%9B%B4)

**Comment by BoyceLig** [comment]
> > 新版本什么时候发？
> 
> ![image](https://user-images.githubusercontent.com/48620527/99214796-13b0bb00-280c-11eb-9d0e-43ea92f82447.png)
> [by HoldOnBro](https://github.com/HoldOnBro/LocalizeCFW#%E6%97%A0%E9%99%90%E6%9C%9F%E5%81%9C%E6%9B%B4)

我也是因为新版本加密了，所以不能汉化了，等有汉化教程或者cfw原生中文

**Comment by yff0216** [comment]
怎么cfw这么垃圾？还加密
