### ISSUE TITLE
怎么汉化呀？

### ISSUE THREAD

**Issue by Linguoyan** [BoyceLig/Clash_Chinese_Patch#100]
小白一枚，把仓库文件下载下来吗？作者说替换 resources/app.asar 文件，用什么替换呀？仓库里也没有包括 app.asar 文件呀？路过的好心人教教呗，感激不尽！

**Comment by viekitelee** [comment]
这是邮箱的自动回复：
            你好!我已经收到你的邮件，如果不是垃圾邮件，有空我会及时回复你。

**Comment by Autuamn** [comment]
去[Releases](https://github.com/BoyceLig/Clash_Chinese_Patch/releases)这里，
下载这个zip包
![image](https://user-images.githubusercontent.com/35159351/207022060-9c6ad17b-a460-4270-9f73-fac49f17d539.png)
