### ISSUE TITLE
0.20.16补充 会导致clash启动失败，启动后clash持续纯白，并且无法操作，只能强制退出

### ISSUE THREAD

**Issue by zxmqq1234** [BoyceLig/Clash_Chinese_Patch#116]
#0.20.16补充
'Make changes to a profile then we merge them for you when you refresh it. <a href="https://docs.cfw.lbyczf.com/contents/diff.html">Docs</a>'==='对配置文件进行更改，程序将会在配置文件更新时自动合并到新的配置文件中。 <a href="https://docs.cfw.lbyczf.com/contents/diff.html">文档</a>'
#0.20.16补充-end 

这一行~ 
  
只要删掉这一行就可以正常使用

**Comment by LightAPIs** [comment]
[ClashSinicizationTool v1.7.0](https://github.com/BoyceLig/ClashSinicizationTool/releases/tag/1.7.0)
