### ISSUE TITLE
替换了没有变化，为什么？

### ISSUE THREAD

**Issue by Aldof-hub** [BoyceLig/Clash_Chinese_Patch#124]
按照介绍，下载解压，然后替换资源下的相同文件，退出软件重进没有任何变化，也没有看到语言设置，为什么呢？

**Comment by BoyceLig** [comment]
没有语言设置，直接是中文，看看是不是替换错文件了

**Comment by Aldof-hub** [comment]
配置好节点后突然自己重启后好了，感谢你的回复。
已解决。这个问题可以删除掉了，谢谢。
