### ISSUE TITLE
没有asar文件，怎么替换。。。有说明嘛😱

### ISSUE THREAD

**Issue by ntf-Cinema4D-sd** [BoyceLig/Clash_Chinese_Patch#128]
两眼一摸黑啊这 。。。
有人知道怎么替换嘛，给的文件里没有asar这个文件。。。

**Comment by BoyceLig** [comment]
去[releases](https://github.com/BoyceLig/Clash_Chinese_Patch/releases)里下载

**Comment by ntf-Cinema4D-sd** [comment]
> 去[releases](https://github.com/BoyceLig/Clash_Chinese_Patch/releases)里下载

帮大忙了！感谢感谢！
