### ISSUE TITLE
Clash core版本问题

### ISSUE THREAD

**Issue by PreGrafer** [BoyceLig/Clash_Chinese_Patch#130]
汉化文件替换后 clashcore的版本停滞在2023.03.04 是否是汉化时忽略了该部分的修改

**Comment by LightAPIs** [comment]
内核和 UI 是分离的，你下载的是哪个版本的 cfw？

**Comment by PreGrafer** [comment]
是最新版啊 直接更新的

**Comment by PreGrafer** [comment]
> 内核和 UI 是分离的，你下载的是哪个版本的 cfw？

·

> 内核和 UI 是分离的，你下载的是哪个版本的 cfw？
是最新版啊 直接更新的

**Comment by PreGrafer** [comment]
> 内核和 UI 是分离的，你下载的是哪个版本的 cfw？

是最新版啊 直接更新
