### ISSUE TITLE
找不到\app.asar这个文件了呀

### ISSUE THREAD

**Issue by liujinTyler** [BoyceLig/Clash_Chinese_Patch#132]
找不到\app.asar这个文件了呀

**Comment by BoyceLig** [comment]
先找到clash的目录，然后找到resources目录，文件就在里边

**Comment by eacnscnj** [comment]
下载下来的文件里找不到\app.asar这个文件？

**Comment by LightAPIs** [comment]
> 下载下来的文件里找不到\app.asar这个文件？

在 Github 网页上右边的 Releases 里下载文件。
