### ISSUE TITLE
翻译遗漏

### ISSUE THREAD

**Issue by MonicaWQY** [BoyceLig/Clash_Chinese_Patch#148]
![image](https://github.com/BoyceLig/Clash_Chinese_Patch/assets/93992899/02163b15-3584-45b2-ba29-d3d872e72156)
![image](https://github.com/BoyceLig/Clash_Chinese_Patch/assets/93992899/dbd809e5-5b46-4961-8162-b3849da830b0)

**Comment by LightAPIs** [comment]
补充后的汉化包：[app.zip](https://github.com/BoyceLig/Clash_Chinese_Patch/files/12711810/app.zip)

**Comment by LightAPIs** [comment]
> > 补充后的汉化包：[app.zip](https://github.com/BoyceLig/Clash_Chinese_Patch/files/12711810/app.zip)
> 
> 这里不知道为什么还是没有显示中文，那个配置那里的提示因为我重新更新了配置，没有提示了，我也不知道汉化成功了木有O.O

那这个包 [app_fixed.zip](https://github.com/BoyceLig/Clash_Chinese_Patch/files/12712052/app_fixed.zip) 日志这里的翻译正常吗？
