### ISSUE TITLE
上游异常：Clash for Windows 疑似删库

### ISSUE THREAD

**Issue by Dragon1573** [BoyceLig/Clash_Chinese_Patch#159]
经实测，本仓库上游 [Fndroid/clash_for_windows_pkg](https://github.com/Fndroid/clash_for_windows_pkg) 已呈现 HTTP 404 异常。

本仓库为 Clash for Windows 的汉化，鉴于上游已消失，请问 Owner 后续有什么计划嘛？是由于失去存在意义而同步归档封存或删库，还是切换为另外的 Fork 分支继续提供汉化？

*****

非常喜欢本仓库提供的汉化效果，使用体验很棒 :heart:

**Comment by buffcow** [comment]
突发，怎么个事😳

**Comment by Dragon1573** [comment]
一切猜测只是小道消息，不具备可信程度，但上游删库的确是事实。

想知道本仓库是否会选择其他Fork作为上游继续汉化。

**Comment by Dragon1573** [comment]
> > 突发，怎么个事😳
> 
> F大佬提交更新时候漏邮箱了，被被约谈删库了

这……

原来大佬没有打开 GitHub 里的邮箱隐私模式和提交邮箱泄露审查的嘛？印象中 GitHub 里有这个功能，当服务器检查到推送上来的提交里有与账号关联的邮箱时会阻止推送。

太可惜了……

**Comment by phb1253439** [comment]
实在是可惜了

**Comment by phb1253439** [comment]
实在是可惜啊

**Comment by LanSnowZ** [comment]
唉 很好的软件啊 RIP

**Comment by huayi1997** [comment]
gg思密达，作者说转用v2ray或者clash verge

**Comment by BoyceLig** [comment]
因为f大停止更新,咱们群后续作为交流群使用。频道不定期转发其他clash的消息。对于汉化后面有新需求再说。
