### ISSUE TITLE
v0.15.2版本的汉化文件替换无效，依然是英文

### ISSUE THREAD

**Issue by TMRware** [BoyceLig/Clash_Chinese_Patch#19]
[](url)
![QQ截图20210413124814](https://user-images.githubusercontent.com/69792408/114498367-8c4e6300-9c56-11eb-92ad-8c3bb4542c8d.png)

**Comment by BoyceLig** [comment]
去群里下载

**Comment by LXY-Tang** [comment]
> 去群里下载

请问如何加群？

**Comment by xiandu999-yu** [comment]
> > 去群里下载
> 
> 请问如何加群？

https://t.me/ClashR_For_Windows
