### ISSUE TITLE
【功能升级】 CFW v0.16.2 已发布，希望尽快同步更新补丁。

### ISSUE THREAD

**Issue by Dragon1573** [BoyceLig/Clash_Chinese_Patch#23]
_Fndroid/clash_for_windows_pkg_ 在2小时前发布了 [_v0.16.2_](https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.16.2) 版本。之前升级到 _v0.16.1_ 时，我发现如果仍使用 _v0.16.0_ 的汉化补丁 `app.asar` ，界面仍能正常被汉化，但软件的版本号会显示为 _v0.16.0_ 而不是 _v0.16.1_ 并持续提醒你进行升级。

作者 @BoyceLig 是否有可能启用 GitHub Actions & Travis CI & Circle CI 等持续集成交付平台，实现自动同步 Clash for Windows 上游源代码，并自动化地生成和发布最新版汉化补丁呢？这样或许能免去被下游用户催更、花费实现人工维护更新补丁的烦恼？

**Comment by Dragon1573** [comment]
v0.16.2 已确认发布

**Comment by BoyceLig** [comment]
做不到自动化
