### ISSUE TITLE
翻译指正

### ISSUE THREAD

**Issue by MSDNicrosoft** [BoyceLig/Clash_Chinese_Patch#24]
建议将 `连接情况` 换成 `连接状态`
![image](https://user-images.githubusercontent.com/69967436/125335735-79474e00-e37f-11eb-832b-b7687d4c3be6.png)

**Comment by BoyceLig** [comment]
好的 下个版本体现

**Comment by MSDNicrosoft** [comment]
> 好的 下个版本体现

好的，感谢采纳建议
