### ISSUE TITLE
代理界面的汉化有个小问题，无法切换到"规则"选项

### ISSUE THREAD

**Issue by chensimmons** [BoyceLig/Clash_Chinese_Patch#25]
经多次测试，感觉是汉化有问题，按说明汉化后，启动软件，一开始代理界面里是默认“规则”选项的，但只要切换到“全局”、“直连”、“脚本”中的任一个，就再也无法切换回“规则”选项，并且其他几个选项可以自由切换，但“规则”选项再也无法点击。去除汉化文件后，就能恢复正常。
操作系统：Windows10 专业版。

<img width="640" alt="搜狗截图20210713153239" src="https://user-images.githubusercontent.com/31755429/125413792-05dd7f60-5ac1-4af3-b74a-8393e6932f0f.png">

**Comment by BoyceLig** [comment]
哪个版本

**Comment by BoyceLig** [comment]
已修复并且从新打包生成
