### ISSUE TITLE
CFW v0.16.4 已发布，希望同步更新汉化

### ISSUE THREAD

**Issue by leezn** [BoyceLig/Clash_Chinese_Patch#26]

**Comment by BoyceLig** [comment]
https://github.com/BoyceLig/Clash_Chinese_Patch/releases/tag/0.16.4

**Comment by BoyceLig** [comment]
不知道为啥  这个不是显示最新

**Comment by Dragon1573** [comment]
> @BoyceLig : 不知道为啥 这个不是显示最新

这可能是 GitHub Releases 的规则？我在 Releases 中看了一下，**v0.16.3** 和 **v0.16.4** 对应的提交哈希（Commit Hash）是同一个，相当于你在这一个 Commit 上打了两个不同的标签。你的源代码没有变动，所以 Releases 认为 **v0.16.3** 和 **v0.16.4** 没有区别，自然 **v0.16.4** 被忽略掉了（尽管收录于 Releases ，但并不认为那是最新版）。

我的建议是，借助 `git commit --allow-empty` 创建一个空白（没有任何内容变更）的、提交哈希完全不同的提交，并在新提交上进行 `app.asar` 文件的发布，这样 Releases 或许就会为新发布添加 "Latest Releases" 标记了。

**Comment by BoyceLig** [comment]
好的 谢谢
