### ISSUE TITLE
汉化遗漏

### ISSUE THREAD

**Issue by MSDNicrosoft** [BoyceLig/Clash_Chinese_Patch#27]
在 Clash For Windows 的 `v.0.17.0` 汉化版本中 `常规` 页面下的 `服务模式` 单击 `管理` 的提示语为英文（如图）
![image](https://user-images.githubusercontent.com/69967436/127766631-88db7299-72aa-40c2-9f6d-5499bef4aa54.png)

**Comment by BoyceLig** [comment]
已修复

**Comment by MSDNicrosoft** [comment]
好的，感谢采纳
