### ISSUE TITLE
配置文件 刷新时间 汉化 的 一个小问题 

### ISSUE THREAD

**Issue by Jxpro** [BoyceLig/Clash_Chinese_Patch#28]
#### 我自己也把asar文件解压，搜索了一遍，但是没有找到对应的说明字段，辛苦作者可以帮忙解决这个问题，辛苦大佬了，万分感谢
![~HJG$T$4)0Y7R J7PWU`%3K](https://user-images.githubusercontent.com/87376573/133102625-b9173206-ee3e-48e8-a757-dde10fdf12e2.png)

**Comment by BoyceLig** [comment]
下个版本看看情况

**Comment by Jxpro** [comment]
好的，学习

**Comment by sgds24** [comment]
![image](https://user-images.githubusercontent.com/74462141/133480556-79f3a04c-e715-454b-aefc-bc1abdb2364e.png)
这个就恐怖了

**Comment by Jxpro** [comment]
对啊 (・・)
