### ISSUE TITLE
有个地方没翻译到

### ISSUE THREAD

**Issue by Mosaic67** [BoyceLig/Clash_Chinese_Patch#3]
![Snipaste_2020-10-11_00-52-30](https://user-images.githubusercontent.com/10384260/95660688-13156c80-0b5c-11eb-93c1-0e6dcd0cf05e.png)

**Comment by BoyceLig** [comment]
好的  下个版本翻译这个 谢谢提供

**Comment by BoyceLig** [comment]
我将翻译成 此配置文件中没有提供程序。

**Comment by Mosaic67** [comment]
这样感觉机翻味道有些浓重，可以加个相应（相关）程序，不知道您觉得怎么样。今天我还发现了一处地方没有翻译，但是没来的及截图，就是弹出win10通知的那个地方，桌面右下角，有个错误提示还是英文的，麻烦您看一下。

**Comment by zonbar** [comment]
自启动也没翻译，在mac版本里还是显示start with macos

**Comment by BoyceLig** [comment]
> 自启动也没翻译，在mac版本里还是显示start with macos

OK
mac的哪里没有翻译到发给我，我统一改一下 你是怎么替换的 给我个教程 我顺便发上  我没有Mac设备

**Comment by BoyceLig** [comment]
> 这样感觉机翻味道有些浓重，可以加个相应（相关）程序，不知道您觉得怎么样。今天我还发现了一处地方没有翻译，但是没来的及截图，就是弹出win10通知的那个地方，桌面右下角，有个错误提示还是英文的，麻烦您看一下。

下次记得截图一下 我这边不报错就出不来 我不知道是哪一句 
你提的建议下个版本修改

**Comment by easyinplay** [comment]
providers 指的代理服务器节点，这里翻译为“此配置中无节点” 会合适一点，纯属个人意见，仅供参考
