### ISSUE TITLE
能否提供 .7z 或 .zip 形式压缩包？

### ISSUE THREAD

**Issue by hall-of-shame** [BoyceLig/Clash_Chinese_Patch#31]
RT.

**Comment by BoyceLig** [comment]
什么？

**Comment by BoyceLig** [comment]
> RT.

rar格式不太行么

**Comment by hall-of-shame** [comment]
> 
> 
> > RT.
> 
> rar格式不太行么

`.rar` 属于 WinRAR，付费工具。

`.7z` 属于 7-zip.org，开源工具。

`.zip` 属于社区通用压缩方案。

**Comment by BoyceLig** [comment]
![image](https://user-images.githubusercontent.com/49801599/139785642-f3a123fd-96f3-427b-a0e8-bc0ab29ba5e9.png)
可以用7z，7z压缩效果最好

**Comment by hall-of-shame** [comment]
谢谢您的付出。🙆‍♀️

**Comment by XYY1411** [comment]
其实 unrar 是免费使用的，rar 是付费使用的。

**Comment by hall-of-shame** [comment]
压缩工具也可以换成 [https://www.7-zip.org/](https://www.7-zip.org/)。
记得配置一下：
- 【开始】菜单中打开 【7-Zip File Manager】
- 菜单栏【工具/Tools】 → 【选项/Options】 → 【7-Zip】
    + 不要勾选【层叠右键菜单/Cascaded context menu】
    + 勾选【右键菜单显示图标/Icons context menu】

配置中，“【选择在右键菜单中显示的项目/Context menu items】” 可以去掉一些不常用的勾选。

**Comment by BoyceLig** [comment]
好的
