### ISSUE TITLE
0.18.10覆盖语言包以后主界面卡在【加载中】多次测试都是这样

### ISSUE THREAD

**Issue by choi006** [BoyceLig/Clash_Chinese_Patch#34]
如题

**Comment by prajna0** [comment]
删除 "cfw-settings.yaml"文件就可以了

**Comment by 52sanmao** [comment]
> 如题解决了没有

**Comment by 52sanmao** [comment]
删除了还是一样加载中的呀

**Comment by BoyceLig** [comment]
删除data文件夹

**Comment by 52sanmao** [comment]
> 删除数据文件夹
数据文件夹是那个呀

**Comment by 52sanmao** [comment]
> 删除数据文件夹

数据文件夹是那个呀

**Comment by BoyceLig** [comment]
> > 删除数据文件夹
> 
> 数据文件夹是那个呀
还有一种可能就是你下载的汉化文件和你当前的clash版本不一致也会导致这样。clash内核自己手动升级也会这样。
不要翻译，那个文件夹就叫data，在clash目录。
![image](https://user-images.githubusercontent.com/49801599/143688293-c3b8e607-3333-4b4a-89c5-3642d8fb12fd.png)

**Comment by choi006** [comment]
确认了没有data这个文件夹
[i1](https://z3.ax1x.com/2021/11/29/oM4vjg.png)
[i2](https://z3.ax1x.com/2021/11/29/oM4W9K.png)

**Comment by BoyceLig** [comment]
你把clash卸载了了  然后从装  删干净。
把文档里的.config/clash删除干净
然后打开看看英文版有问题没  没问题再替换汉化，再打开看看

![image](https://user-images.githubusercontent.com/49801599/143831183-73623099-c1b1-4c68-aea5-57120a5420fa.png)

**Comment by choi006** [comment]
确认了没有data这个文件夹
![i1](https://z3.ax1x.com/2021/11/29/oM4vjg.png)
![i2](https://z3.ax1x.com/2021/11/29/oM4W9K.png)

**Comment by choi006** [comment]
> 你把clash卸载了了 然后从装 删干净。 把文档里的.config/clash删除干净 然后打开看看英文版有问题没 没问题再替换汉化，再打开看看
> 
> ![image](https://user-images.githubusercontent.com/49801599/143831183-73623099-c1b1-4c68-aea5-57120a5420fa.png)

按操作试了一遍。替换了中文汉化包还是不行(英语始终是正常的)

**Comment by BoyceLig** [comment]
版本对应么   汉化版本必须对应clash

**Comment by choi006** [comment]
> 版本对应么 汉化版本必须对应clash

版本是对应的

**Comment by BoyceLig** [comment]
如果还有问题就点击这个私信我  我远程给你看看 https://t.me/Boyce_Lig

**Comment by choi006** [comment]
我切回英语语言包了。我等下一次汉化再试试吧。楼上那几个兄弟应该也遇到了一样的问题。公司电脑不方便远程

**Comment by BoyceLig** [comment]
用工具手动汉化一下试试吧

**Comment by BoyceLig** [comment]
群友说：开启系统代理后再重启软件试试

**Comment by BoyceLig** [comment]
右键任务栏图标可以开启代理和重启

**Comment by 52sanmao** [comment]
再尝试许多方法之后，我将resources文件夹的几个文件删除之后得以解决。只保留了这个几个，具体问题是出再哪里的，我也不知道
![Uploading 48798.png…]()

**Comment by BoyceLig** [comment]
0.18.10 安装版本汉化后界面如果这样这样，可以删除 "config.yaml" 文件试试，如果还不行就暂时先用英文版。

**Comment by charley008** [comment]
试试删除 c：\users\用户\appdata\roaming\clash_win

**Comment by choi006** [comment]
今天更新了0.19.1。这个版本的汉化是正常没有问题的

**Comment by viekitelee** [comment]
这是邮箱的自动回复：
            你好!我已经收到你的邮件，如果不是垃圾邮件，有空我会及时回复你。
