### ISSUE TITLE
[Bug]: 在"设置"→"配置"里配置文件目录时的"打开"窗口只能选择文件,正常情况下为选择一个文件夹,未汉化版本则没有这个问题

### ISSUE THREAD

**Issue by Plutonium141** [BoyceLig/Clash_Chinese_Patch#35]
在选择配置文件目录时的窗口只能选择文件,正常情况下为选择一个文件夹,未汉化版本则没有这个问题
版本为 0.19.0
![chinese1](https://user-images.githubusercontent.com/62324696/144616447-fa634f1f-8a33-415c-a5db-cf467edc30db.jpg)
![english](https://user-images.githubusercontent.com/62324696/144616436-50f646af-d513-4d70-8497-9f12b982239f.jpg)
![chinese](https://user-images.githubusercontent.com/62324696/144616450-144445bb-c3f1-44af-b94c-a1bb988a5749.jpg)

**Comment by BoyceLig** [comment]
之前的版本有这个问题么

**Comment by Plutonium141** [comment]
> 之前的版本有这个问题么

0.18.0就有这个问题了

**Comment by BoyceLig** [comment]
这个我简单的看了一下，有点棘手，暂时先用着 我先查着

**Comment by Plutonium141** [comment]
> 这个我简单的看了一下，有点棘手，暂时先用着 我先查着

好的 这个bug并不严重只要把正确的路径填到旁边的输入框中就可以正常使用

**Comment by BoyceLig** [comment]
直接原releases里下载就行，已修复后替换
