### ISSUE TITLE
发现一个不需要汉化而汉化的了导致的显示问题

### ISSUE THREAD

**Issue by lvzhenbo** [BoyceLig/Clash_Chinese_Patch#40]
![image](https://user-images.githubusercontent.com/32427677/150469192-ccc31abb-5df4-4f1c-9d02-84b989525355.png)
![image](https://user-images.githubusercontent.com/32427677/150469216-1074175b-97f2-46cf-800b-cfe854a2258c.png)
如图，R被翻译成了规则

**Comment by BoyceLig** [comment]
因为她是rule   伤及无辜了可能 我查查

**Comment by BoyceLig** [comment]
https://github.com/BoyceLig/Clash_Chinese_Patch/releases/tag/0.19.6
