### ISSUE TITLE
0.19.11 在 删除配置文件对话框 点叉时会直接删除配置文件

### ISSUE THREAD

**Issue by WangHaonie** [BoyceLig/Clash_Chinese_Patch#43]
在 删除配置文件对话框 点叉时会直接删除配置文件
使用原版英文的 app.asar 不会出现这个问题

汉化版：
![cfw](https://user-images.githubusercontent.com/68315280/156870098-6d9c5fa8-bb0a-4e49-abce-15a676ff15ec.gif)

原版：
![cfw_e](https://user-images.githubusercontent.com/68315280/156870174-ed5f6962-1892-4236-8951-c7dbc296dcd1.gif)

**Comment by BoyceLig** [comment]
https://github.com/BoyceLig/Clash_Chinese_Patch/releases/tag/0.19.11%EF%BC%88%E8%A1%A5%E5%85%85%E7%BF%BB%E8%AF%91%EF%BC%89
