### ISSUE TITLE
Not Found v0.19.12

### ISSUE THREAD

**Issue by chenghm123** [BoyceLig/Clash_Chinese_Patch#44]

**Comment by viekitelee** [comment]
这是邮箱的自动回复：
            你好!我已经收到你的邮件，如果不是垃圾邮件，有空我会及时回复你。

**Comment by BoyceLig** [comment]
你用汉化 还发英文

**Comment by King-Nameless** [comment]
gkd，出13了![image](https://user-images.githubusercontent.com/83447487/160198762-7b33d9b1-e8fe-491d-a3e0-74339dd4352a.png)

**Comment by lawshon** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
