### ISSUE TITLE
最新版已经出来咯。

### ISSUE THREAD

**Issue by daloyanf** [BoyceLig/Clash_Chinese_Patch#47]
快快更新吧，兄弟！

**Comment by Discover999** [comment]
这才刚出，等一会就好了

**Comment by forsthetwo** [comment]
出现·了替换后没有·变化的问题，win11

**Comment by BoyceLig** [comment]
> 出现·了替换后没有·变化的问题，win11

替换错了吧，是还是英文版吗

**Comment by forsthetwo** [comment]
> > 出现·了替换后没有·变化的问题，win11
> 
> 替换错了吧，是还是英文版吗

没有哦，之前的版本按同样方法替换是有用的，只有这次替换完以后还是英文的

**Comment by BoyceLig** [comment]
> > > 出现·了替换后没有·变化的问题，win11
> > 
> > 
> > 替换错了吧，是还是英文版吗
> 
> 没有哦，之前的版本按同样方法替换是有用的，只有这次替换完以后还是英文的

你替换错了，亲测TG上和GitHub上下载的替换都是中文版，要不就是你目录替换错了，要不就是你电脑有多份cfw，你替换的和你打开的不是一个cfw
