### ISSUE TITLE
找见个地方没翻译

### ISSUE THREAD

**Issue by Mosaic67** [BoyceLig/Clash_Chinese_Patch#5]
在设置中设置了切换模式的快捷键，Clash会弹出系统通知，系统通知没有翻译
![Snipaste_2020-10-23_21-06-24](https://user-images.githubusercontent.com/10384260/97007238-b2caf580-1573-11eb-99d6-13d305943f78.png)

**Comment by BoyceLig** [comment]
汉化好了
