### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by 227ZZT** [BoyceLig/Clash_Chinese_Patch#51]
dalao你好，请问怎么覆盖呢？是把asar删除在把这三个文件或者下载的整个文件夹放到resource文件夹吗

**Comment by 227ZZT** [comment]
可是我下载的Clash_Chinese_Patch-main压缩包里只有一个JAVA文件，一个文本文档和一个MD文件，没有发现asar文件呢~

**Comment by 0ne0ay** [comment]
> 可是我下载的Clash_Chinese_Patch-main压缩包里只有一个JAVA文件，一个文本文档和一个MD文件，没有发现asar文件呢~

1  ![Screenshot_20220602-115151_Chrome_Beta~3](https://user-images.githubusercontent.com/12570708/171549833-3a20d48c-8bc5-415f-b04a-6775d0eb0679.png)
2  ![Screenshot_20220602-115348_Chrome_Beta~3](https://user-images.githubusercontent.com/12570708/171549853-556c8de4-5032-4593-a368-068820bd4da7.png)

**Comment by 227ZZT** [comment]
哦哦！找到了，多谢大佬帮助
