### ISSUE TITLE
出新版本了更新

### ISSUE THREAD

**Issue by luluxiaomi** [BoyceLig/Clash_Chinese_Patch#53]
出新版本了更新

**Comment by hope140** [comment]
> 出新版本了更新

汉化要时间，最好周六更新

**Comment by MacMonterey** [comment]
是的
----- 原始邮件 -----
发件人：Hope ***@***.***>
收件人：BoyceLig/Clash_Chinese_Patch ***@***.***>
抄送人：Subscribed ***@***.***>
主题：Re:_[BoyceLig/Clash_Chinese_Patch]_出新版本了更新_(Issue_#53)
日期：2022年06月17日 18点41分





出新版本了更新



汉化要时间，最好周六更新



&mdash;

**Comment by MacMonterey** [comment]
我忽然发现0.19.20的多开好像有问题
----- 原始邮件 -----
发件人：Hope ***@***.***>
收件人：BoyceLig/Clash_Chinese_Patch ***@***.***>
抄送人：Subscribed ***@***.***>
主题：Re:_[BoyceLig/Clash_Chinese_Patch]_出新版本了更新_(Issue_#53)
日期：2022年06月17日 18点41分





出新版本了更新



汉化要时间，最好周六更新



&mdash;

**Comment by AnyWAT** [comment]
某人有病？
有人说：中国人写的东西，没有中文。。。
敝人回了本仓的地址，然后被那里的仓主屏蔽了，嘿嘿。详：
https://github.com/Fndroid/clash_for_windows_pkg/issues/3313

**Comment by BoyceLig** [comment]
> 某人有病？ 有人说：中国人写的东西，没有中文。。。 敝人回了本仓的地址，然后被那里的仓主屏蔽了，嘿嘿。详： [Fndroid/clash_for_windows_pkg#3313](https://github.com/Fndroid/clash_for_windows_pkg/issues/3313)

F大也早早把我给屏蔽了。

**Comment by AnyWAT** [comment]
貌似版本号错了：
不是 v0.20.1 
而是 v0.20.2

**Comment by LightAPIs** [comment]
> 

v0.20.1 有问题，被下架了，现在只能看到 v0.20.2 版本的包了。
