### ISSUE TITLE
发现个没未翻译地方

### ISSUE THREAD

**Issue by Mosaic67** [BoyceLig/Clash_Chinese_Patch#8]
![image](https://user-images.githubusercontent.com/10384260/98076859-0f021380-1eaa-11eb-9919-dc1d9d574b05.png)

点击版本号会提示更新，弹出仍未英文。

**Comment by BoyceLig** [comment]
![image](https://user-images.githubusercontent.com/49801599/98097955-ab3b1300-1ec8-11eb-874a-71b865c6ceaf.png)
好了
