### ISSUE TITLE
可以这里也翻译吧

### ISSUE THREAD

**Issue by xivi1839** [BoyceLig/Clash_Chinese_Patch#89]
求翻译，求汉化
![_20221011015352](https://user-images.githubusercontent.com/24610024/194926031-19699ce4-9017-4aa7-a0cb-85c8792ac0ae.png)

**Comment by LightAPIs** [comment]
[Releases](https://github.com/BoyceLig/Clash_Chinese_Patch/releases/tag/0.20.5) 里 `app_time_added.zip`/`app_time_added.7z` 的包是已经补充翻译过时间了呀。

**Comment by xivi1839** [comment]
感谢解决，我换app_time_added的就好了
