### ISSUE TITLE
13.2后的汉化

### ISSUE THREAD

**Issue by sigang88** [BoyceLig/Clash_Chinese_Patch#9]
我就想知道13.2后的汉化要怎么弄

**Comment by BoyceLig** [comment]
暂时不汉化了，能汉化的部分是右键的菜单

**Comment by sigang88** [comment]
哦

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Boyce Lig<mailto:notifications@github.com>
发送时间: 2020年11月13日 SIGANG 13:45
收件人: BoyceLig/Clash_Chinese_Patch<mailto:Clash_Chinese_Patch@noreply.github.com>
抄送: sigang88<mailto:sigang@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [BoyceLig/Clash_Chinese_Patch] 13.2后的汉化 (#9)


暂时不汉化了，能汉化的部分是右键的菜单

―
