### ISSUE TITLE
作者您好，我发现一个收费下载clash的网站

### ISSUE THREAD

**Issue by SleepySheepnw** [BoyceLig/Clash_Chinese_Patch#99]
网站链接为[https://www.hereitis.cn/soft/clashforwindowshhb]，下载方式为登录后开通会员才能登陆
![image](https://user-images.githubusercontent.com/76431529/204135444-08cd2eb4-8159-437c-9ecb-3cf2d9e60cbb.png)

**Comment by BoyceLig** [comment]
早就发现了，警告了没用
